---
- name: Install LAMP
  hosts: all
  become: yes

  vars:
        source_folder: ./users_list
        destin_folder: /var/www/html


  tasks:
    - name: install lamp stack
      become: yes
      become_user: root
      apt:
        pkg:
          - apache2
          - mysql-server
          - php7.4
          - php7.4-mysql
        state: present
        update_cache: yes

    - name: start apache service
      become: yes
      become_user: root
      service:
        name: apache2
        state: started
        enabled: yes

    - name: start mysql service
      become: yes
      become_user: root
      service:
        name: mysql
        state: started
        enabled: yes

    - name: create target directory
      file: path=/var/www/html state=directory mode=0755

    - name: copy
      copy: src={{ source_folder }} dest={{ destin_folder }} mode=0555
      notify: Restart apache
     
  handlers:
    - name: Restart apache
      service: name=apache2 state=restarted
